#!/usr/bin/env bash
set -e
mkdir -p assets
echo "Downloading remote assets..."
echo "Fetching header_dark.png"; curl -L -o assets/header_dark.png "https://capsule-render.vercel.app/api?type=waving&color=0d1117&height=280&section=header&text=Aman%20Anubhav&fontSize=80&fontAlignY=35&animation=fadeIn&fontColor=ffffff&desc=Machine%20Learning%20Engineer%20%7C%20Researcher%20%7C%20Founder&descAlignY=55&descSize=20" || wget -O assets/header_dark.png "https://capsule-render.vercel.app/api?type=waving&color=0d1117&height=280&section=header&text=Aman%20Anubhav&fontSize=80&fontAlignY=35&animation=fadeIn&fontColor=ffffff&desc=Machine%20Learning%20Engineer%20%7C%20Researcher%20%7C%20Founder&descAlignY=55&descSize=20"
echo "Fetching header_light.png"; curl -L -o assets/header_light.png "https://capsule-render.vercel.app/api?type=waving&color=ffffff&height=280&section=header&text=Aman%20Anubhav&fontSize=80&fontAlignY=35&animation=fadeIn&fontColor=0d1117&desc=Machine%20Learning%20Engineer%20%7C%20Researcher%20%7C%20Founder&descAlignY=55&descSize=20" || wget -O assets/header_light.png "https://capsule-render.vercel.app/api?type=waving&color=ffffff&height=280&section=header&text=Aman%20Anubhav&fontSize=80&fontAlignY=35&animation=fadeIn&fontColor=0d1117&desc=Machine%20Learning%20Engineer%20%7C%20Researcher%20%7C%20Founder&descAlignY=55&descSize=20"
echo "Fetching summit.jpg"; curl -L -o assets/summit.jpg "https://raw.githubusercontent.com/half-s/half-s/main/assets/summit.jpg" || wget -O assets/summit.jpg "https://raw.githubusercontent.com/half-s/half-s/main/assets/summit.jpg"
echo "Fetching typing.svg"; curl -L -o assets/typing.svg "https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=500&size=24&pause=1000&color=39FF14&center=true&vCenter=true&width=500&lines=Building+AI+Agents+with+Gemini+3;Solving+DSA+in+C%2FC%2B%2B;Predicting+FinTech+Trends;Scaling+Communities+Globally" || wget -O assets/typing.svg "https://readme-typing-svg.herokuapp.com?font=Fira+Code&weight=500&size=24&pause=1000&color=39FF14&center=true&vCenter=true&width=500&lines=Building+AI+Agents+with+Gemini+3;Solving+DSA+in+C%2FC%2B%2B;Predicting+FinTech+Trends;Scaling+Communities+Globally"

echo "All assets downloaded into the ./assets directory."
